name: notify line count

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: [ubuntu-latest]
    steps:
      - name: Notify PR LineCount
        uses: naver/notify-pr-line-count@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
          slackChannelId: "C07UWE43Y2J"
          maxChanges: "300"
          ext: ".java"
          glob: "packages/**, !**/node_modules/*"